### ISSUE TITLE
gw.apply?

### ISSUE THREAD

**Issue by mmann1123** [jgrss/satsmooth#1]
Can this be applied with gw apply functions? @jgrss

**Comment by jgrss** [comment]
I think it's possible. Although, perhaps it might be easier to use [Xarray.DataArray.map_blocks](https://xarray.pydata.org/en/v0.14.1/generated/xarray.DataArray.map_blocks.html)?

**Comment by mmann1123** [comment]
That's a good thought. I hadn't seen that.
