### ISSUE TITLE
_signal

### ISSUE THREAD

**Issue by mmann1123** [jgrss/satsmooth#4]
@jgrss after install I am getting:
```
>>> import satsmooth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmann1123/Documents/github/satsmooth/satsmooth/__init__.py", line 1, in <module>
    from .detect import peaks_valleys1d, peaks_valleys2d, group_peaks_valleys2d, phenometrics1d, phenometrics2d
  File "/home/mmann1123/Documents/github/satsmooth/satsmooth/detect/__init__.py", line 1, in <module>
    from ._signal import peaks_valleys1d, peaks_valleys2d, group_peaks_valleys2d, phenometrics1d, phenometrics2d
ModuleNotFoundError: No module named 'satsmooth.detect._signal'
```

I am seeing a `_signal.pyx` and `_signal.c`  so its not clear to me what is happening. Any quick ideas?

**Comment by jgrss** [comment]
Hey @mmann1123, how did you install `satsmooth`? The source build should only include `.pyx` files. When installing the Cython files (i.e., `.pyx`), corresponding `.so` files should be generated on Linux and `.pyd` files on Windows. The `.c` files are generated during the process, but are not used in the imports. If you are missing a `.so` or `.pyd` then they didn't compile correctly.

**Comment by mmann1123** [comment]
@jgrss  

I initially installed with `python setup.py build && python setup.py install` as suggested for linux. 

Getting a very similar error installing on conda-forge.  Here's a [link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=796634&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=683).   The build is throwing a lot of warnings not seeing any errors

**Comment by mmann1123** [comment]
It all looks like giberish to me but my syntax highlighter is complaining about [this](https://github.com/jgrss/satsmooth/blob/614fa32750ed25b378b2095ed7d1dfb9fdf4c04c/satsmooth/detect/_signal.pyx#L748C56-L748C56)

**Comment by jgrss** [comment]
Can you try to install [this branch](https://github.com/jgrss/satsmooth/tree/jgrss/setup)? I rearranged files and updated the setup process in #6.

**Comment by mmann1123** [comment]
@jgrss That worked off the pip install
